name: iamsarahv
favicon: null
layout_spectrum: 0.4178527460899204
typography_spectrum: 0.543657825095579
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#10110b'
    - '#38421b'
    - '#cbc9ce'
    - '#814e3f'
    - '#b67964'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.6663966136984527
  rhythmicContrast: 0.9169253678992391
purpose: []
